### ISSUE TITLE
Error when Start paper 1.18.1 Server 

### ISSUE THREAD

**Issue by M2tecDev** [zhenghanlee/LargeRaids#2] opened 2021-12-31 10:04 UTC
[20:31:26] [Server thread/ERROR]: Error occurred while enabling LargeRaids v1.8.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getBoolean(String)" because "titleConfig" is null
	at com.solarrabbit.largeraids.config.RaidConfig.<init>(RaidConfig.java:34) ~[LargeRaids.jar:?]
	at com.solarrabbit.largeraids.LargeRaids.onEnable(LargeRaids.java:64) ~[LargeRaids.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-101]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:31:26] [Server thread/INFO]: [LargeRaids] Disabling LargeRaids v1.8.2

**Comment by solarrabbit99** [comment] 2021-12-31 17:39
This is most likely a duplicate of #1

**Comment by solarrabbit99** [comment] 2022-01-18 00:00
Closing issue due to inactivity

**Closed as completed by solarrabbit99** 2022-01-18 00:00 UTC
